variables:
  CONTAINER: 'https://ityeblob.blob.core.windows.net/repo'
  CHARTNAME: 'presidio'
  #SASTOKEN: '<token>'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: HelmInstaller@0
  displayName: 'Install Helm 2.9.1'

- bash: |
   cd charts
   curl $CONTAINER/index.yaml > index.yaml
   helm package $CHARTNAME
   helm repo index --merge index.yaml .
   TAR=$(ls *tgz)
   
   curl -X PUT -T ./$TAR -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "$CONTAINER/$TAR?$SASTOKEN"
   
   curl -X PUT -T ./index.yaml -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "$CONTAINER/index.yaml?$SASTOKEN"
  displayName: 'Bash Script'
